version: '3.1'

services:
   db:
     image: mariadb:10.6.14
     volumes:
       - db:/var/lib/mysql
     ports:
       - 3306:3306
     networks:
      - krisinet
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    networks:
      - krisinet
    volumes:
      - wordpress:/var/www/html
      - ./plugins/wp-graphql-woocommerce:/var/www/html/wp-content/plugins/wp-graphql-woocommerce
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    env_file:
      - .env
    depends_on:
      - db
        
   nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - krisinet

networks:
  krisinet:
    driver: bridge

volumes:
  wordpress:
  db: