name: Deploy to Hetzner VPS

on:
  workflow_run:
    workflows: [docker-publish]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: SSH into Hetzner VPS and run deploy.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HETZNER_SSH_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          script: |
            chmod +x ${{ vars.HETZNER_DEPLOY_SCRIPT }}
            cd /root/krisi-shop
            sh ${{ vars.HETZNER_DEPLOY_SCRIPT }}