name: Deploy to Hetzner VPS

on:
  workflow_run:
    workflows: [docker-publish]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Hetzner VPS and run deploy.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HETZNER_SSH_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          script: |
            chmod +x ${{ env.HETZNER_DEPLOY_SCRIPT }}
            sh ${{ env.HETZNER_DEPLOY_SCRIPT }}